services:
  #localization:
  #  image: stzdiego/stz.localizationservice:latest
  #  environment:
  #    ASPNETCORE_URLS: "http://+:80;https://+:443"
  #    ASPNETCORE_ENVIRONMENT: "Development"
  #    ASPNETCORE_Kestrel__Certificates__Default__Path: "/app/certs/shared.pfx" 
  #    ASPNETCORE_Kestrel__Certificates__Default__Password: "1234567890"
  #    Logging__LogLevel__Default: "Information"
  #    Logging__LogLevel__Microsoft.AspNetCore: "Warning"
  #    ConnectionStrings__DefaultConnection: "Server=host.docker.internal;Port=5432;Database=STZ.ResourceManager;User Id=postgres;Password=postgres;"
  #    AllowedHosts: "*"
  #    MigrationAssembly: "STZ.LocalizationService.Backend"
  #  ports:
  #    - "7111:80"
  #    - "7110:443"
  #  volumes:
  #    - ./certs:/app/certs

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio-server
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Consola web
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  minio_data: